/** @jsxImportSource @emotion/react */
import { Card, CardDeck } from "@gamepark/nidavellir/cards/Cards";
import Images from "../images/Images";
import { CardDescription } from "@gamepark/react-game/dist/components/material/FlatMaterial/CardDescription";

export class DwarfCardDescription extends CardDescription {
  width = 5.4
  ratio = 54 / 80
  borderRadius = 0.3

  backImages = {
    [CardDeck.Age1]: Images.Age1Back,
    [CardDeck.Age2]: Images.Age2Back
  }

  images = {
    [Card.BlacksmithDwarf1Age1] : Images.BlacksmithDwarf1Age1,
    [Card.BlacksmithDwarf1Age2] : Images.BlacksmithDwarf1Age2,
    [Card.BlacksmithDwarf2Age1] : Images.BlacksmithDwarf2Age1,
    [Card.BlacksmithDwarf2Age2] : Images.BlacksmithDwarf2Age2,
    [Card.BlacksmithDwarf3Age1] : Images.BlacksmithDwarf3Age1,
    [Card.BlacksmithDwarf3Age2] : Images.BlacksmithDwarf3Age2,
    [Card.BlacksmithDwarf4Age1] : Images.BlacksmithDwarf4Age1,
    [Card.BlacksmithDwarf4Age2] : Images.BlacksmithDwarf4Age2,
    [Card.BlacksmithDwarf5Age1] : Images.BlacksmithDwarf5Age1,
    [Card.BlacksmithDwarf5Age2] : Images.BlacksmithDwarf5Age2,
    [Card.BlacksmithDwarf6Age1] : Images.BlacksmithDwarf6Age1,
    [Card.BlacksmithDwarf6Age2] : Images.BlacksmithDwarf6Age2,
    [Card.BlacksmithDwarf7Age1] : Images.BlacksmithDwarf7Age1,
    [Card.BlacksmithDwarf7Age2] : Images.BlacksmithDwarf7Age2,
    [Card.BlacksmithDwarf8Age1] : Images.BlacksmithDwarf8Age1,
    [Card.BlacksmithDwarf8Age2] : Images.BlacksmithDwarf8Age2,
    [Card.BlacksmithDwarf9Age1] : Images.BlacksmithDwarf9Age1,
    [Card.BlacksmithDwarf9Age2] : Images.BlacksmithDwarf9Age2,
    [Card.BlacksmithDwarf10Age1] : Images.BlacksmithDwarf10Age1,
    [Card.BlacksmithDwarf10Age2] : Images.BlacksmithDwarf10Age2,
    [Card.BlacksmithDwarfKingsGreatArmorer] : Images.BlacksmithDwarfKingsGreatArmorer,
    [Card.ExplorerDwarf1Age1] : Images.ExplorerDwarf1Age1,
    [Card.ExplorerDwarf1Age2] : Images.ExplorerDwarf1Age2,
    [Card.ExplorerDwarf2Age1] : Images.ExplorerDwarf2Age1,
    [Card.ExplorerDwarf2Age2] : Images.ExplorerDwarf2Age2,
    [Card.ExplorerDwarf3Age1] : Images.ExplorerDwarf3Age1,
    [Card.ExplorerDwarf3Age2] : Images.ExplorerDwarf3Age2,
    [Card.ExplorerDwarf4Age1] : Images.ExplorerDwarf4Age1,
    [Card.ExplorerDwarf4Age2] : Images.ExplorerDwarf4Age2,
    [Card.ExplorerDwarf5Age1] : Images.ExplorerDwarf5Age1,
    [Card.ExplorerDwarf5Age2] : Images.ExplorerDwarf5Age2,
    [Card.ExplorerDwarf6Age1] : Images.ExplorerDwarf6Age1,
    [Card.ExplorerDwarf6Age2] : Images.ExplorerDwarf6Age2,
    [Card.ExplorerDwarf7Age1] : Images.ExplorerDwarf7Age1,
    [Card.ExplorerDwarf7Age2] : Images.ExplorerDwarf7Age2,
    [Card.ExplorerDwarf8Age1] : Images.ExplorerDwarf8Age1,
    [Card.ExplorerDwarf8Age2] : Images.ExplorerDwarf8Age2,
    [Card.HunterDwarf1Age1] : Images.HunterDwarf1Age1,
    [Card.HunterDwarf1Age2] : Images.HunterDwarf1Age2,
    [Card.HunterDwarf2Age1] : Images.HunterDwarf2Age1,
    [Card.HunterDwarf2Age2] : Images.HunterDwarf2Age2,
    [Card.HunterDwarf3Age1] : Images.HunterDwarf3Age1,
    [Card.HunterDwarf3Age2] : Images.HunterDwarf3Age2,
    [Card.HunterDwarf4Age1] : Images.HunterDwarf4Age1,
    [Card.HunterDwarf4Age2] : Images.HunterDwarf4Age2,
    [Card.HunterDwarf5Age1] : Images.HunterDwarf5Age1,
    [Card.HunterDwarf5Age2] : Images.HunterDwarf5Age2,
    [Card.HunterDwarf6Age1] : Images.HunterDwarf6Age1,
    [Card.HunterDwarf6Age2] : Images.HunterDwarf6Age2,
    [Card.HunterDwarf7Age1] : Images.HunterDwarf7Age1,
    [Card.HunterDwarf7Age2] : Images.HunterDwarf7Age2,
    [Card.HunterDwarf8Age1] : Images.HunterDwarf8Age1,
    [Card.HunterDwarf8Age2] : Images.HunterDwarf8Age2,
    [Card.MinerDwarf1Age1] : Images.MinerDwarf1Age1,
    [Card.MinerDwarf1Age2] : Images.MinerDwarf1Age2,
    [Card.MinerDwarf2Age1] : Images.MinerDwarf2Age1,
    [Card.MinerDwarf2Age2] : Images.MinerDwarf2Age2,
    [Card.MinerDwarf3Age1] : Images.MinerDwarf3Age1,
    [Card.MinerDwarf3Age2] : Images.MinerDwarf3Age2,
    [Card.MinerDwarf4Age1] : Images.MinerDwarf4Age1,
    [Card.MinerDwarf4Age2] : Images.MinerDwarf4Age2,
    [Card.MinerDwarf5Age1] : Images.MinerDwarf5Age1,
    [Card.MinerDwarf5Age2] : Images.MinerDwarf5Age2,
    [Card.MinerDwarf6Age1] : Images.MinerDwarf6Age1,
    [Card.MinerDwarf6Age2] : Images.MinerDwarf6Age2,
    [Card.MinerDwarf7Age1] : Images.MinerDwarf7Age1,
    [Card.MinerDwarf7Age2] : Images.MinerDwarf7Age2,
    [Card.MinerDwarf8Age1] : Images.MinerDwarf8Age1,
    [Card.MinerDwarf8Age2] : Images.MinerDwarf8Age2,
    [Card.RoyalOffering1Age1] : Images.RoyalOffering1Age1,
    [Card.RoyalOffering1Age2] : Images.RoyalOffering1Age2,
    [Card.RoyalOffering2Age1] : Images.RoyalOffering2Age1,
    [Card.RoyalOffering2Age2] : Images.RoyalOffering2Age2,
    [Card.RoyalOffering3Age2] : Images.RoyalOffering3Age2,
    [Card.WarriorDwarf1Age1] : Images.WarriorDwarf1Age1,
    [Card.WarriorDwarf1Age2] : Images.WarriorDwarf1Age2,
    [Card.WarriorDwarf2Age1] : Images.WarriorDwarf2Age1,
    [Card.WarriorDwarf2Age2] : Images.WarriorDwarf2Age2,
    [Card.WarriorDwarf3Age1] : Images.WarriorDwarf3Age1,
    [Card.WarriorDwarf3Age2] : Images.WarriorDwarf3Age2,
    [Card.WarriorDwarf4Age1] : Images.WarriorDwarf4Age1,
    [Card.WarriorDwarf4Age2] : Images.WarriorDwarf4Age2,
    [Card.WarriorDwarf5Age1] : Images.WarriorDwarf5Age1,
    [Card.WarriorDwarf5Age2] : Images.WarriorDwarf5Age2,
    [Card.WarriorDwarf6Age1] : Images.WarriorDwarf6Age1,
    [Card.WarriorDwarf6Age2] : Images.WarriorDwarf6Age2,
    [Card.WarriorDwarf7Age1] : Images.WarriorDwarf7Age1,
    [Card.WarriorDwarf7Age2] : Images.WarriorDwarf7Age2,
    [Card.WarriorDwarf8Age1] : Images.WarriorDwarf8Age1,
    [Card.WarriorDwarf8Age2] : Images.WarriorDwarf8Age2,
    [Card.WarriorDwarf9Age1] : Images.WarriorDwarf9Age1,
    [Card.WarriorDwarf9Age2] : Images.WarriorDwarf9Age2,
    [Card.BlacksmithDwarfKingsGreatArmorer]: Images.BlacksmithDwarfKingsGreatArmorer,
    [Card.Bonfur]: Images.Bonfur,
    [Card.Aegur]: Images.Aegur,
    [Card.Dagda]: Images.Dagda,
    [Card.Aral]: Images.Aral,
    [Card.Kraal]: Images.Kraal,
    [Card.Tarah]: Images.Tarah,
    [Card.Lokdur]: Images.Lokdur,
    [Card.Zoral]: Images.Zoral,
    [Card.Idunn]: Images.Idunn,
    [Card.Hourya]: Images.Hourya,
    [Card.Astrid]: Images.Astrid,
    [Card.DwergYmir]: Images.DwergYmir,
    [Card.DwergAesir]: Images.DwergAesir,
    [Card.DwergSigmir]: Images.DwergSigmir,
    [Card.DwergJungir]: Images.DwergJungir,
    [Card.DwergBergelmir]: Images.DwergBergelmir,
    [Card.Thrud]: Images.Thrud,
    [Card.Ylud]: Images.Ylud,
    [Card.Skaa]: Images.Skaa,
    [Card.Uline]: Images.Uline,
    [Card.Grid]: Images.Grid,
  }

  rules = () => <p></p>
}

export const cardDescription = new DwarfCardDescription()
